doctrine:
  dbal:
    driver: %podorozhny.database.driver%
    host: %podorozhny.database.host%
    port: %podorozhny.database.port%
    dbname: %podorozhny.database.name%
    user: %podorozhny.database.user%
    password: %podorozhny.database.password%
    charset: UTF8
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    mappings:
      frontend:
        type: yml
        dir: "%kernel.root_dir%/../src/Podorozhny/CoreBundle/Resources/config/doctrine/frontend"
        prefix: Podorozhny\Model\Frontend
        alias: Frontend
        is_bundle: false
      shop:
        type: yml
        dir: "%kernel.root_dir%/../src/Podorozhny/CoreBundle/Resources/config/doctrine/shop"
        prefix: Podorozhny\Model\Shop
        alias: Shop
        is_bundle: false
      support:
        type: yml
        dir: "%kernel.root_dir%/../src/Podorozhny/CoreBundle/Resources/config/doctrine/support"
        prefix: Podorozhny\Model\Support
        alias: Support
        is_bundle: false