parameters:
  podorozhny.mailer.mailgun.api_key: ~
  podorozhny.mailer.mailgun.public_api_key: ~
  podorozhny.mailer.mailgun.domain: bmstushop.local

  podorozhny.mailer.contact.template: CoreBundle:Email:contact.html.twig
  podorozhny.mailer.contact.from_address: backend@bmstushop.local
  podorozhny.mailer.contact.from_name: %podorozhny.company.name% Backend
  podorozhny.mailer.contact.to_address: ivan@podorozhny.ru
  podorozhny.mailer.contact.to_name: 'Ivan Podorozhny'

  podorozhny.mailer.customer_welcome.template: CoreBundle:Email:customer_welcome.html.twig
  podorozhny.mailer.customer_welcome.from_address: welcome@bmstushop.local
  podorozhny.mailer.customer_welcome.from_name: %podorozhny.company.name%

services:
  mailgun:
    class: Mailgun\Mailgun
    arguments:
      - %podorozhny.mailer.mailgun.api_key%

  podorozhny.mailer:
    class: Podorozhny\Mailer\MailgunMailer
    arguments:
      - @mailgun
      - @twig
      - %podorozhny.mailer.mailgun.domain%

  podorozhny.mailer.contact:
    class: Podorozhny\Mailer\Support\ContactMailer
    arguments:
      - @podorozhny.mailer
      - { template: '%podorozhny.mailer.contact.template%', from_address: '%podorozhny.mailer.contact.from_address%', from_name: '%podorozhny.mailer.contact.from_name%', to_address: '%podorozhny.mailer.contact.to_address%', to_name: '%podorozhny.mailer.contact.to_name%' }

  podorozhny.mailer.customer_welcome:
    class: Podorozhny\Mailer\Frontend\CustomerWelcomeMailer
    arguments:
      - @podorozhny.mailer
      - { template: '%podorozhny.mailer.customer_welcome.template%', from_address: '%podorozhny.mailer.customer_welcome.from_address%', from_name: '%podorozhny.mailer.customer_welcome.from_name%' }