parameters:
  podorozhny.sms.smsru.api_id:      ~
  podorozhny.sms.smsru.login:       ~
  podorozhny.sms.smsru.password:    ~
  podorozhny.sms.smsru.sender_name: 'BMSTUShop'

services:
  smsru:
    class: Zelenin\Smsru
    calls:
      - [setApiId, [%podorozhny.sms.smsru.api_id%]]
      - [setLogin, [%podorozhny.sms.smsru.login%]]
      - [setPassword, [%podorozhny.sms.smsru.password%]]

  podorozhny.sms.sender:
    class: Podorozhny\Sms\Sender
    arguments:
      - @smsru
      - %podorozhny.sms.smsru.sender_name%