#shop_product_list:
#  pattern: /products
#  defaults:
#    _controller: podorozhny.shop.controller.product:listAction
#  requirements:
#    _method: GET

shop_product_show:
  pattern: /product/{product_slug}
  defaults:
    _controller: podorozhny.shop.controller.product:showAction
  requirements:
    _method: GET
    product_slug: .+