Podorozhny\Model\Shop\ProductPhoto:
  type: entity
  table: shop_product_photos
  repositoryClass: Podorozhny\Repository\Shop\ProductPhotoRepository
  manyToOne:
    product:
      targetEntity: Podorozhny\Model\Shop\Product
      inversedBy: photos
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    createdAt:
      column: created_at
      type: datetime
    updatedAt:
      column: updated_at
      type: datetime
      nullable: true
    path:
      type: string
      length: 1024