services:
  podorozhny.frontend.controller.security:
    class: Podorozhny\CoreBundle\Controller\Frontend\SecurityController
    parent: podorozhny.controller.abstract
    arguments:
      - @form.csrf_provider

  podorozhny.frontend.controller.registration:
    class: Podorozhny\CoreBundle\Controller\Frontend\RegistrationController
    parent: podorozhny.controller.abstract
    arguments:
      - @podorozhny.frontend.registration.form.factory
      - @podorozhny.frontend.user_manager

  podorozhny.frontend.controller.page:
    class: Podorozhny\CoreBundle\Controller\Frontend\PageController
    parent: podorozhny.controller.abstract