frontend_security_login:
  pattern: /login
  defaults:
    _controller: podorozhny.frontend.controller.security:loginAction

frontend_security_check:
  pattern: /login_check
  requirements:
    _method: POST

frontend_security_logout:
  pattern: /logout